### ISSUE TITLE
wasm support

### ISSUE THREAD

**Issue by happydpc** [jkb0o/pecs#4]
Can it work with wasm build? if it supports, then the http request with bevy will be easy.

**Comment by nikolajevs86** [comment]
I suppose it is not working, at least for me it is not compiling for wasm:
 <img width="901" alt="Screenshot 2023-03-12 at 16 17 25" src="https://user-images.githubusercontent.com/44358443/224550707-608e4b2c-135e-4c87-85d8-6679a1210f0c.png">

But I am sure that ehttp is able to use for wasm as I am using it directly with some workarounds for bevy.
Anyway big thanks  to Yasha for creating this plugin as I thought today to implement it based on the ehttp, but luckily decided to check if there is something already implemented and was really surprised :D 
Maybe @jkb0o can share if there are some plans to implement support for the wasm?

**Comment by jkb0o** [comment]
Sorry for the late response. I've added wasm support. Http examples however spawn CORS-related errors. It should be ok if you request owned resources: https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS/Errors/CORSMissingAllowOrigin

**Comment by nikolajevs86** [comment]
Awesome news, thanks a lot!

**Comment by happydpc** [comment]
Thanks for your help, I will give it a try.
