### ISSUE TITLE
update to bevy 0.10

### ISSUE THREAD

**Issue by happydpc** [jkb0o/pecs#5]
I have tried to upgrade to 0.10,  but the self.body not satisfy the trait into_system

```rust 
 let system = write.entry(key).or_insert_with(|| {
            let mut sys = Box::new(IntoSystem::into_system(self.body));
            sys.initialize(world);
            sys
        });
```

**Comment by jkb0o** [comment]
Yeah, it is not so easy to convert function pointers to systems for now. I'll try to figure it out in the next two days or rewrite this part.

Thank you for report!
